/**
 * The site's tables, in Postgres: CloudNativePG in production, a container
 * locally (ADR 0011). People, sessions, sites (organizations), members,
 * invitations, device codes, and SSO providers are Better Auth's tables, in
 * auth-schema.ts, generated by `bun run auth:schema` (ADR 0013). After changing
 * either file, `bun run db:generate` writes the migration.
 */
import {
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { organization } from './auth-schema.ts';

export * from './auth-schema.ts';

const ts = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const policies = pgTable(
  'policies',
  {
    siteId: text('site_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(),
    body: jsonb('body').$type<Record<string, unknown>>().notNull(),
    note: text('note'),
    createdBy: text('created_by'),
    createdAt: ts('created_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.siteId, t.version] })],
);

export const usageDaily = pgTable(
  'usage_daily',
  {
    siteId: text('site_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    date: text('date').notNull(),
    tier: text('tier', { enum: ['local', 'remote'] }).notNull(),
    provider: text('provider').notNull(),
    model: text('model').notNull(),
    calls: integer('calls').notNull(),
    inputTokens: integer('input_tokens').notNull(),
    outputTokens: integer('output_tokens').notNull(),
    cacheReadTokens: integer('cache_read_tokens').notNull(),
    costUsd: doublePrecision('cost_usd').notNull(),
  },
  (t) => [primaryKey({ columns: [t.siteId, t.userId, t.date, t.tier, t.provider, t.model] })],
);

export const telemetryReports = pgTable(
  'telemetry_reports',
  {
    installId: text('install_id').notNull(),
    day: text('day').notNull(),
    siteId: text('site_id').references(() => organization.id, { onDelete: 'set null' }),
    report: jsonb('report').notNull(),
    receivedAt: ts('received_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.installId, t.day] }), index('telemetry_by_day').on(t.day)],
);

export const auditLog = pgTable(
  'audit_log',
  {
    id: text('id').primaryKey(),
    siteId: text('site_id').references(() => organization.id, { onDelete: 'cascade' }),
    actorId: text('actor_id'),
    action: text('action').notNull(),
    detail: text('detail'),
    at: ts('at').notNull(),
  },
  (t) => [index('audit_by_site').on(t.siteId, t.at)],
);
